---
title: "main"
output: pdf_document
date: "2024-07-20"
---


```{r}
# importing necessary libraries 

library(tidyverse)
library(rlang)
library(ggpubr)
library(pheatmap)


# import the csv
series_matrix<- read.csv('./data/QBS103_GSE157103_series_matrix.csv')
genes <- read.csv('./data/QBS103_GSE157103_genes.csv')

# example code for finding the package version and citations 

# packageVersion('tidyverse')
# packageVersion('rlang')
# packageVersion('pheatmap')
# citation('ggpubr')
```


```{r}

# function to transpose/prepare the data from series_matrix and genes

prepare_dataframe <- function(series_matrix, genes){
  unique(series_matrix$age) # this one is covariate 

  # let's merge these two data sets together 
  
  # transpose the genes dataframe
  transposed_genes <- as.data.frame(t(genes))
  colnames(transposed_genes) <- genes$X
  transposed_genes <- transposed_genes[2:length(genes), ]
  

  for (i in colnames(transposed_genes)){
    series_matrix[[i]] <- as.numeric(transposed_genes[[i]]) # convert the transposed data to numeric
  }
  return(series_matrix)
}

dataframe <- prepare_dataframe(series_matrix, genes)
dataframe <- subset(dataframe, sex != " unknown")

# discrete
# sex, icu_status, disease_status 

# continuous 
# age, ferritin.ng.ml, charlson_score

# Select the chosen discrete and continious variables
selected_dataframe <- dataframe[c('sex', 'icu_status', 'disease_status', 'age', 'ferritin.ng.ml.', 'crp.mg.l.')]

# ensure that they are treated as numeric
selected_dataframe$age <- as.numeric(selected_dataframe$age)
selected_dataframe$ferritin.ng.ml. <- as.numeric(selected_dataframe$ferritin.ng.ml.)
selected_dataframe$crp.mg.l. <- as.numeric(selected_dataframe$crp.mg.l.)

table(selected_dataframe$sex)

# find the divider for calculation of n%
divider <- as.numeric(sum(table(selected_dataframe$disease_status)))

# generate the summary table
summary_table <- selected_dataframe %>% 
  dplyr::group_by(sex) %>% 
  dplyr::summarise(`Age (mean) (years)` = mean(age, na.rm = TRUE),
                   `Age (sd) (years)` = sd(age, na.rm = TRUE),
                   `Ferritin (mean) (ng/ml)` = mean(ferritin.ng.ml., na.rm =  TRUE),
                   `Ferritin (sd) (ng/ml)` = sd(ferritin.ng.ml., na.rm = TRUE),
                   `CRP (mean) (mg/l)` = mean(crp.mg.l., na.rm = TRUE),
                   `CRP (sd) (mg/l)` = sd(crp.mg.l., na.rm = TRUE),
                   `Disease Status (n%)` = table(disease_status)/divider * 100,
                   `Sex (n%)` = table(sex)/divider * 100,
                   `ICU Status (n%)` = table(icu_status)/divider * 100
                    )

# In order to calculate summary statistics of n% for male and female seperately, the following code was used

a <- subset(dataframe, sex == "Male")
table(a$disease_status)/sum(table(a$disease_status))
table(a$icu_status)/sum(table(a$icu_status))

b <- subset(dataframe, sex == "Female")
table(b$disease_status)/sum(table(b$disease_status))
table(b$icu_status)/sum(table(b$icu_status))

```

```{r}
# https://stackoverflow.com/questions/55132771/standard-eval-with-ggplot2-without-aes-string/55133909#55133909 
# source used form !!sym (to pass a string as a symbol in an aes environment)


generate_plots <- function(dataframe, list_of_genes, continuous_variable, categorical_covariates)
  {
  # This the continuous variables
  # plots scatter
  
  for (gene in list_of_genes){
    print(gene)
    print(continuous_variable)
    scatter <- ggplot(dataframe, aes(x = !!sym(continuous_variable)
                                     , y = !!sym(gene), color = sex)) +
    geom_point() + 
    xlab('Age (years)') + 
    ylab(paste(gene, ' Expression')) + 
    scale_x_discrete(breaks = seq(0, 100, by = 10)) + 
    ggtitle(paste( "Expression of ", gene, " vs Age")) + 
    labs(color = "Sex") + 
    theme_classic() 
  

    # this is for the two categorical variables
    # plot the box plot
    box <- ggplot(dataframe, aes(y = !!sym(gene),
                                 x = !!sym(categorical_covariates[1]),
                                 fill = !!sym(categorical_covariates[2]))) +
      geom_boxplot(names(c('COVID', 'NON-COVID'))) +
      labs(x = categorical_covariates[1], y = gene) + 
      scale_x_discrete(labels = c("disease state: COVID-19" = "COVID-19", 
                                  "disease state: non-COVID-19" = "non COVID-19")) +
      theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8))  + 
      ggtitle(paste(gene, "Expression by disease status", "and", categorical_covariates[2])) + theme_classic()

    # plot the histogram
    print(gene)
    histo <- ggplot(dataframe, aes(x = !!sym(gene))) +
    geom_histogram() +
    theme_classic() + 
    ggtitle(paste( "Expression of ", gene))

    # save the plots 
    ggsave("boxplot.png", plot = box)
    ggsave("scatterplot.png", plot = scatter)
    ggsave("histogram.png", plot = histo)

    return (list(box, histo, scatter))
  }
  
}

plots <- generate_plots(dataframe, c('A2M'), 'age', c('disease_status', 'sex') )
plots[1]
plots[2]
plots[3]
```
```{r}

# select 10 genes
genes_vector <- c("A2M", "AASDHPPT", "AASS", "AATF", "AATK", "ABAT", "ABCA1", "ABCA10", "ABCA12", "ABCA13", "ABCA2")

# create a dataframe with those genes
gene_df <- select(dataframe, genes_vector)

# generate the annotation dataframe
annotation <- select(dataframe, c("sex", "disease_status"))  # Include 'sex' and 'disease_status

# rename for clarity 
annotation$disease_status <- ifelse(annotation$disease_status=="disease state: COVID-19", 'COVID-19', 'non-COVID-19')
annotation$sex <- ifelse(annotation$sex==" female", 'Female', 'Male')
colnames(annotation) <- c('Sex', 'Disease Status')

# transpose gene dataframe for heatmap generation
transposed_ndf <- t(gene_df)

# generate the heatmap using euclidean clustering
pheatmap(transposed_ndf, 
         clustering_distance_rows = "euclidean", 
         clustering_distance_cols = "euclidean", 
         clustering_method = "complete",
         scale = "row",
         annotation_col = annotation, 
         show_colnames = FALSE)

```

```{r}
# Generate a QQ plot 
dataframe$sex <- ifelse(dataframe$sex==" female", 'Female', 'Male')

ggplot(dataframe, aes(sample = A2M)) +
  stat_qq(aes(color = sex)) +
  scale_color_manual(values = c("#00AFBB", "#E7B800"))+
  labs(y = "Expression of A2M") + 
  theme_classic() + 
  ggtitle('QQ plot of A2M Expression') + 
  xlab('Theoretical Normal Distribution') +
  labs(color = "Sex") 
  ggsave(('qq_plot.png'))


```
 